# Print a new line before prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
# symbol = "➜"     # The "symbol" segment is being set to "➜"
style_success = "blue"
style_failure = "red"

[cmd_duration]
min_time = 0
show_milliseconds = true
prefix = ""
style = "yellow"

[directory]
truncation_length = 3
truncate_to_repo = true
prefix = ""
style = "purple"
