# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "16384"
    vb.cpus = "8"
  end

  config.trigger.after :up, :provision do |t|
    scriptpath = File.join(Dir.home, "setup-scripts", "vagrant", "scripts")

    t.run_remote = {
      args: $LANGUAGES,
      path: File.join(scriptpath, "setup_user_unprivileged.sh"),
      privileged: false,
    }
  end
end
